### ISSUE TITLE
Use as library

### ISSUE THREAD

**Issue by ibotty** [fpco/pid1#2]
It would be nice to have a function `run' :: IO () -> IO ()` which takes care of all pid-1-stuff and runs the "real" IO action.

I assume that it needs some documentation of the limitations that apply (signal handlers).

**Comment by snoyberg** [comment]
I specifically avoided that because of the problems it can cause, including
signals, but also breaking any calls into the process package. I'd
recommend having your application take a command line argument to
distinguish parent and child, and then have the parent run itself using
this library.

**Comment by ibotty** [comment]
> I specifically avoided that because of the problems it can cause, including
> signals, but also breaking any calls into the process package.

When running the main app as PID 1, you don't need to propagate any
signal. Can you elaborate on the problems that will be caused? In
particularly regarding the process package?

**Comment by snoyberg** [comment]
pid1 will run an infinite loop reaping orphans by calling `waitpid`. This works when the pid1 process isn't also calling `waitForProcess` on processes it spawned. However, if the same process is doing both, then you'll have a race condition of whether the loop will get the exit code or the `waitForProcess` call.

**Comment by psibi** [comment]
I'm closing this issue as there is no actionable item in this repo, free feel to re-open if you disagree.
