### ISSUE TITLE
Is pid1 available via apk?

### ISSUE THREAD

**Issue by richard-browne** [fpco/pid1#9]
Hi I want to use sed1 in an Alpine docker image. But it doesn't exist in the package repo, apparently:

`apk add --no-cache pid1`

> ERROR: unsatisfiable constraints:
>   pid1 (missing):
>    required by: world[pid1]
> The command '/bin/sh -c apk add --no-cache pid1' returned a non-zero code: 1

**Comment by snoyberg** [comment]
Correct, we don't build an Alpine package.

**Comment by richard-browne** [comment]
Bummer. Please consider it.

**Comment by psibi** [comment]
If you want to add this to your apline docker image, you could do this:

```
ADD https://github.com/fpco/pid1/releases/download/v0.1.3.1/pid1 /usr/bin/pid1
RUN chmod +x /usr/bin/pid1
```

I'm closing this issue as there is no actionable item in this repo, free feel to re-open if you disagree.
